### ISSUE TITLE
SyntaxWarning: invalid escape sequence '\.' python 3.12.

### ISSUE THREAD

**Issue by GiorgosXou** [GiorgosXou/TUIFIManager#111]
Since python 3.12 this kind of warnings appeared, I just solved them them but the one which is visible and intercepts the program, might need  to be fixed manually by user ...

https://github.com/home-assistant/core/issues/110263

**Comment by GiorgosXou** [comment]
it's the one cause by the `cmds.conf` entry `"yat | copy | 'pattern':'.+\.txt'``

**Comment by GiorgosXou** [comment]
ok I think i solved it

**Comment by GiorgosXou** [comment]
# 👋 FIX Here 
go to `~/.config/tuifi/cmds.conf` and change `"yat | copy | 'pattern':'.+\.txt'..` to `"yat | copy | 'pattern':'.+\\.txt'..`

**Comment by Sigmanificient** [comment]
You could use raw string `r'.+\.txt'`, they are meant for storing things like regex pattern that can have "illegal character sequences"

**Comment by GiorgosXou** [comment]
@Sigmanificient  it's due to variable evaluation:
https://github.com/GiorgosXou/TUIFIManager/blob/1ccb8f255d1ae43bef240fdd024bb7a8f67e9bbe/TUIFIManager/__init__.py#L1102

<sup>*(Discord disabled my account btw :/ | Probably due to experimenting with their private api)*</sup>

**Comment by Sigmanificient** [comment]
you may want to refactor that line
```py
            ln = line.split('|') #  command, args, type, comment | using "|" because this is an __illegal_filename_characters
            self.command_events[ln[0].strip()] = (self.command_types[ln[1].strip()], ast.literal_eval('{'+ln[2].strip()+'}'), ln[3].strip())
```
```py
            cmd, args, typ, comment = map(str.strip, line.split('|'))  # using "|" because this is an __illegal_filename_characters
            self.command_events[cmd] = (self.command_types[args], ast.literal_eval('{'+typ+'}'), comment)
```
