### ISSUE TITLE
Shortcut "`ctrl+e` > exit with cd" (non rooted) & command `yd`, not working 

### ISSUE THREAD

**Issue by cargilcm** [GiorgosXou/TUIFIManager#121]
## *Specifications*
- OS: `Android 12 aarch` 
- Terminal: `termux` 
- TUIFI Version: `v.5.0.0` 

## *Describe the bug*
The top most call in the execution stack is logged below:
`File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/TUIFIManager/TUItilities.py", line 49, in put_text_back_into_terminal_input_buffer
    for c in text: ioctl(1, TIOCSTI, c)
                   ^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied`

## *Additional context*
I found [a SO post](https://stackoverflow.com/a/29615101/377241) that says the process must have root privileges for ioctl tiocsti operations to succeed.  It would be nice if the cd path could be assigned to an variable that bash could call ie: `bash -c cd $cdpath` manually after tuifi exits if ioctl permissions are prohibitive. The error that is thrown by python crashes the terminal tab also so no further text can be displayed when typed  after this type of exit. Let me know if you desire to see the whole stack trace from stderr.

Thank you

**Comment by cargilcm** [comment]
The command yd doesn't work for me either but without putting on my code inspector goggles my first guess is that the yd command calls a function that uses tiocsti too lol 

![Screenshot_20241109-193857](https://github.com/user-attachments/assets/c9e788fa-3fb2-464b-bb40-18b1ac99e6c2)

**Comment by GiorgosXou** [comment]
Thanks for the catch! I forgot to add that, here's the fix: https://github.com/GiorgosXou/TUIFIManager/commit/a4f79922fc9c47ff0d691acfabbab3ea087a6eb2

<sup>*(Additional info for anyone coming across this issue, you do also need to install [this](https://f-droid.org/packages/com.termux.api/) and `pkg install termux-api`)*</sup>

**Comment by GiorgosXou** [comment]
> The top most call in the execution stack is logged below:
File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/TUIFIManager/TUItilities.py", line 49, in put_text_back_into_terminal_input_buffer for c in text: ioctl(1, TIOCSTI, c) ^^^^^^^^^^^^^^^^^^^^ PermissionError: [Errno 13] Permission denied

Yes, that's a trick only available for root devices, **but** I just found that it might be possible too, via this way https://github.com/gokcehan/lf/issues/140#issuecomment-464910159

**Comment by cargilcm** [comment]
Awesome, I love tuifi and I especially love your passion for programming and keeping others on the up with your attention to their input etc

Thank you, Giorgios, really..as to the lf program's scripts I think this is what can be hoped for alternative to iocntl because I learned to you can't set environment variables that persist beyond the life of the process(& subprocesses) in Python so yes you have to do some bash scripting (and to tweak possibly __main__.py so that after endwin it prints os.getcwd() or maybe the selected file?  I'll upload some code and share what I use for "-last-directory" with the autojump program.

Thank You, Giorgos

**Comment by GiorgosXou** [comment]
Instaed of tweaking `main.py` I guess you could replace:
https://github.com/GiorgosXou/TUIFIManager/blob/a4f79922fc9c47ff0d691acfabbab3ea087a6eb2/TUIFIManager/__init__.py#L637-L638
from:
https://github.com/GiorgosXou/TUIFIManager/blob/a4f79922fc9c47ff0d691acfabbab3ea087a6eb2/TUIFIManager/__init__.py#L636-L642
with what you are trying to do.

**Comment by GiorgosXou** [comment]
https://github.com/GiorgosXou/TUIFIManager/issues/85

**Comment by GiorgosXou** [comment]
if this works https://github.com/gokcehan/lf/issues/140#issuecomment-464910159, I'll simply ditch the root-trick completly. I just don't have the time right now to test it.

**Comment by cargilcm** [comment]
Lf's exit with CD directs the session location to the relevant directory but lf is written in go which I had wondered was there something special in the go binaries different from pythons that allowed their program to achieve this. I have some other quirks that are not meeting my needs with the documented behavior or tuifi not playing out as described (non rooted termux issues again I think) but I'll file those under different support tickets, appropriately.  I had noticed other tui file managers writing the files to a file and currently that's my only way of knowing how to solve the issue and I had just finished my commit solving that way when I broke my termux by a faulty alias in bashrc  back to coding at base level zero lol 

Thanks Giorgos!

**Comment by cargilcm** [comment]
> > The top most call in the execution stack is logged below:
> > File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/TUIFIManager/TUItilities.py", line 49, in put_text_back_into_terminal_input_buffer for c in text: ioctl(1, TIOCSTI, c) ^^^^^^^^^^^^^^^^^^^^ PermissionError: [Errno 13] Permission denied
> 
> Yes, that's a trick only available for root devices, **but** I just found that it might be possible via this way [gokcehan/lf#140 (comment)](https://github.com/gokcehan/lf/issues/140#issuecomment-464910159), too. Once I find the time I'll see what I can do, but...
> 
> > I'm glad if I can write some code to this end to help out
> 
> ... feel free to do so, if you like.

**Comment by GiorgosXou** [comment]
> when navigating from TERMUX_HOME to shared storage will only get you back to TERMUX_HOME via a previously set marker...

You don't need a marker,  just use the `HOME` button:
![Screenshot_2024-12-01-12-01-49-012_com termux_1](https://github.com/user-attachments/assets/9312ffc8-56d8-41cd-a8cc-eeb086702211)

**Comment by cargilcm** [comment]
Seeing how your are the author of unicurses I would feel mostly certain that it doesn't remain unknown yet that piping the output of a python curses program will most likely include control séquences and escape characters that are hard to filter out but to use the tuifi program's command line output "you" could (read: I am) use `endwin()` followed by a custom escape sequence (`//`) at the end of the control flow of TUIFIManager and assign that value from AWK to a bash variable ie CD_dir after which your bash function executes `cd $CD_dir` like the lf program does.  I am happy to pass along my .bashrc with this functionality and or __init__.py and __main__.py files I used if you'd like. 

Can I submit via pull request?  For my research, I'm giving this an"issue closed" tag.  Fwiw if `newterm` -juggling were possible [like here](https://stackoverflow.com/a/72266910/377241) I would like that.

Reiteration, TUIFIManager and ecosystem for my learning about curses gets a double thumbs up

**Comment by cargilcm** [comment]
Seeing how your are the author of unicurses I would feel mostly certain that it doesn't remain unknown yet that piping the output of a python curses program will most likely include control séquences and escape characters that are hard to filter out but to use the tuifi program's command line output "you" could (read: I am) use `endwin()` followed by a custom escape sequence (`//`) at the end of the control flow of TUIFIManager and assign that value from AWK to a bash variable ie CD_dir after which your bash function executes `cd $CD_dir` like the lf program does.  I am happy to pass along my .bashrc with this functionality and or __init__.py and __main__.py files I used if you'd like. 

Can I submit via pull request?  For my research, I'm giving this an"issue closed" tag.  Fwiw if `newterm` -juggling were possible [like here](https://stackoverflow.com/a/72266910/377241) I would like that.

Reiteration, TUIFIManager and ecosystem for my learning about curses gets a double thumbs up

**Comment by cargilcm** [comment]
Seeing how your are the author of unicurses I would feel mostly certain that it doesn't remain unknown yet that piping the output of a python curses program will most likely include control séquences and escape characters that are hard to filter out but to use the tuifi program's command line output "you" could (read: I am) use `endwin()` followed by a custom escape sequence (`//`) at the end of the control flow of TUIFIManager and assign that value from AWK to a bash variable ie CD_dir after which your bash function executes `cd $CD_dir` like the lf program does.  I am happy to pass along my .bashrc with this functionality and or __init__.py and __main__.py files I used if you'd like. 

Can I submit via pull request?  For my research, I'm giving this an"issue closed" tag.  Fwiw if `newterm` -juggling were possible [like here](https://stackoverflow.com/a/72266910/377241) I would like that.

Reiteration, TUIFIManager and ecosystem for my learning about curses gets a double thumbs up

**Comment by GiorgosXou** [comment]
> Seeing how your are the author of unicurses

Not the author, just a maintainer.

> Can I submit via pull request? 

Feel free to do so. Or simply link me to your fork changes and I'll do the the rest by my own (while ensuring to [co-author](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors#creating-co-authored-commits-on-github) you), as I'm concerned of few things that may need to be changed.

**Comment by cargilcm** [comment]
I think I have committed a working tuifi-cd if you will command. In my bash I have named it `tuify` and if you use setup.py to install with my init you still need to click escape after cntl+e since exit() is not called after handle_garbage () .  Should I have moved the end win and print statements to just under "if not Windows" to replace self.cd like you mentioned? 

How does this attempt look to you?

**Comment by GiorgosXou** [comment]
Looks ok.

Don't worry, I'll fix what's needed once I have the time,  right now I'm working on another project and that's why I'm not active on the issue. 

Thanks

**Comment by GiorgosXou** [comment]
Unfortunately, some CLI applications (e.g., [Neovim](https://github.com/neovim/neovim/issues/30156)) are not fully compatible with `tee`. Additionally, suspending tasks or applications *(via `Ctrl+Z`)* introduces further issues that disrupt functionality. **Due to these limitations,** I had to abandon your solution and implement a new one instead: https://github.com/GiorgosXou/TUIFIManager/commit/96fe5aa0f938a36c291509a2094c557787e18a26 https://github.com/GiorgosXou/TUIFIManager/commit/d817b67deda619d8da502bbd794d756b9bb3e596

**Comment by cargilcm** [comment]
Pretty cool! 

I needed something like this:
alias tuifi='function _tuifi(){
  # Run tuifi                                                tuifi
  pydir="$(python -c "from tempfile import gettempdir;print(gettempdir())")/tuifi_last_path.txt"
  # Check if path exists in this virtual file system (stor>
  if [ -e /dev/shm/tuifi_last_path.txt ]; then
    cd "$(</dev/shm/tuifi_last_path.txt)"
#    rm /dev/shm/tuifi_last_path.txt
  fi
  if [ -e "$pydir" ]; then
    cd "$(<"$pydir")"
  fi
  echo "done"
}; _tuifi'


And gettempdir() doesn't end with a '/' so add that at line 635 of init.py.

And that should do.

**Comment by GiorgosXou** [comment]
> And gettempdir() doesn't end with a '/' so add that at line 635 of init.py.

True, thanks for the catch! I'm going to push a new version right now

**Comment by GiorgosXou** [comment]
@cargilcm use:
```sh
# Set to Fasle if you don't want to exit with escape but only with ctrl+e
tuifi_cd_on_esc=True tuifi
cd "$(<"$pydir")"
```
I just made an update right now

**Comment by cargilcm** [comment]
I sent you a coffee-Merry Christmas Giorgos

**Comment by GiorgosXou** [comment]
Hope your Christmas is as wonderful as you are, thank u so much! Have a great new year and feel always free to ask me anything if you even need any help about tuifi

**Comment by GiorgosXou** [comment]
*(**Small edit:** added `"$@"` to `tuifi_cd_on_esc=True tuifi "$@"` for argument passing)*

**Comment by GiorgosXou** [comment]
Termux --> cd on esc:
```
alias tuifi='function _tuifi() {
  tuifi_cd_on_esc=True tuifi "$@"
  cd "$(</data/data/com.termux/files/usr/tmp/tuifi_last_path.txt)"
}; _tuifi'
```
