### ISSUE TITLE
TUIFIManager does not start in current working directory.

### ISSUE THREAD

**Issue by paxsali** [GiorgosXou/TUIFIManager#4]
Hello,

I see no reason why TUIFIManager should not start in the current working directory `$PWD` (`os.path.curdir` in Python).

Instead, it appears the default is to always start in the user's home directory (`$HOME`).

Please consider changing the behavior.

**Comment by GiorgosXou** [comment]
Indeed,  I kinda agree,  although *(something I haven't mentioned)* you can always just do `tuifi .` or whatever path

**Comment by GiorgosXou** [comment]
[v.1.1.3](https://github.com/GiorgosXou/TUIFIManager/blob/master/CHANGELOG.md)
