### ISSUE TITLE
FIle formats not supported

### ISSUE THREAD

**Issue by TanmayPatil105** [GiorgosXou/TUIFIManager#46]
## Following file formats are currently not supported:
- `.docx`
- `.csv`
- `.pptx`
- `.ppt`
- `.odp`

**Comment by TanmayPatil105** [comment]
Can you assign me the issue?

**Comment by GiorgosXou** [comment]
Feel free to post any icon recommendation here:
https://github.com/GiorgosXou/TUIFIManager/issues/37

**Comment by TanmayPatil105** [comment]
Sure 👍!!

**Comment by TanmayPatil105** [comment]
Closing this issue!!
