### ISSUE TITLE
Display Hidden files after Non-Hidden files

### ISSUE THREAD

**Issue by TanmayPatil105** [GiorgosXou/TUIFIManager#47]
Not sure this is an `issue` but displaying both hidden and non-hidden files/folders together makes it kinda messy for the user to distinguish.
Normally, `non-hidden` files are displayed first and then the hidden files at last.
Also, a `shortcut` can be created to `unhide` hidden files and to `hide` again.

**Comment by GiorgosXou** [comment]
https://github.com/GiorgosXou/TUIFIManager/releases/tag/v.3.0.0
