### ISSUE TITLE
Flickering of menu (?)

### ISSUE THREAD

**Issue by GiorgosXou** [GiorgosXou/TUIFIManager#62]
For some very wierd reason, the issue **gets solved** the momment I open a file to an external app *(it doesn't matter if the external app is a TUI or not)*, I'm guessing this has to do with the `print(BEGIN_MOUSE)` in main

\r vs \n vs \r\n etc.

![tuifi_Peek 2023-01-05 11-53](https://user-images.githubusercontent.com/11987271/210752053-22e96e7a-9de8-4a0c-941e-a8d2632cb9fc.gif)

**Comment by GiorgosXou** [comment]
THAT"S  SO WIERD

**Comment by GiorgosXou** [comment]
Ha... there's might be a need of reinitialization *(BEGIN...END_MOUSE)* when a new pad *(like the menu)* is created

**Comment by GiorgosXou** [comment]
I think it has to do with the ncurses itself, thinking that the mouse escape sequences are part of a change to the stdscr, forcing it to redraw itself again and again

**Comment by GiorgosXou** [comment]
I need to make a minimal reproducible example before I post the issue and i don't know if I have the time to do so... but I have to do so...

**Comment by GiorgosXou** [comment]
> ...  forcing it to redraw itself again and again (?)

But if this is true, then why it gets fixed the momment I `END_MOUSE` > suspend the app > open a subprocess > waint until it closes > `BEGIN_MOUSE` ??? 

https://github.com/GiorgosXou/TUIFIManager/blob/dcc17d820f565cb70df5c1719dda423c0af09809/TUIFIManager/__init__.py#L251

**Comment by GiorgosXou** [comment]
May the lord of ncurses Thomas E. Dickey , saves me 🙏

**Comment by GiorgosXou** [comment]
*(or anyone else lol)*

**Comment by GiorgosXou** [comment]
Ok ok... I'll try to make a minimal reproducible example in c\c++ when i find the time

**Comment by GiorgosXou** [comment]
**The Issue is completly random, I can't pinpoint when it is happening** besides that when it is happening, it gets solved by doing what i've said in the first comment

**Comment by GiorgosXou** [comment]
Sometimes it just works without flickering and some times it doesn't 
||
|:---:|
|![image](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fmedia.giphy.com%2Fmedia%2FCaiVJuZGvR8HK%2Fgiphy.gif&f=1&nofb=1&ipt=1b839c6b0488c81069a2cbaa70d14047d00e538d13af7a5a09b9ad3ac4a3ed56&ipo=images)|

**Comment by GiorgosXou** [comment]
Intersections and redrawing is something that ncurses handles by itself during refresh *(really efficiently actually)*, it's not that much of our business to handle them. Also even if we wanted, [this issue kinda prevents as at the momment](https://github.com/unicurses/unicurses/issues/21)

`Rect` and `Drawable` are somewhat equivalent to the ncurses-`WINDOW`\`pad` [...]  **This issue apears from nowhere** and I don't really know what is causing it really, besides that when it *(randomly)* appears **on startup** it gets solved the momment I do what i've said at the first comment

**Comment by GiorgosXou** [comment]
*Do you expirience the same issue too?*

**Comment by Sigmanificient** [comment]
> _Do you expirience the same issue too?_ (just to make sure)

I need to check

**Comment by Sigmanificient** [comment]
> Do you expirience the same issue too?
It doesn't seem to flicker, but it something isn't properly rendered

![image](https://user-images.githubusercontent.com/53050011/210856852-41551fc6-225f-42c1-bdef-be2920cf0700.png)
![image](https://user-images.githubusercontent.com/53050011/210857037-0ee40b3e-2a5f-4696-868c-fdfc1a775645.png)

**Comment by Sigmanificient** [comment]
I guess having a rendering pipeline (without checking for collision) could be a good idea, so that everything is indexed properly, and the ui part is extracted

**Comment by GiorgosXou** [comment]
on those images you posted is you terminal smaller that 20 rows?

**Comment by Sigmanificient** [comment]
Base size:
![image](https://user-images.githubusercontent.com/53050011/210857831-40928693-4a68-41cb-a485-eb06408d206d.png)

Bigger:
![image](https://user-images.githubusercontent.com/53050011/210857890-8cc8a11c-7521-4f5e-94d3-44daebb3ff8d.png)

**Comment by GiorgosXou** [comment]
This is another issue, it is related to the fact that when you right click, the terminal is too small to either open the menu on top or at the bottom of the position where you clicked, and such it crops it

**Comment by GiorgosXou** [comment]
maybe a smaller menu might be great

**Comment by GiorgosXou** [comment]
if you click on one of the upper icons or expand the terminal even more this issue disapears, this is easilly fixable, the real issue is with the flickering

**Comment by GiorgosXou** [comment]
Here's the bad implementation of the positioning of the menu :P
https://github.com/GiorgosXou/TUIFIManager/blob/5b45e00ba4902318b75586a49e3dfeb1b3ce568d/TUIFIManager/TUIMenu.py#L53

**Comment by GiorgosXou** [comment]
Here you go,  now it's better

https://github.com/GiorgosXou/TUIFIManager/commit/73f0d4c00c5f298a40e9404e46f06d01219604e4
